exporter.baseDirectory = ./output/
exporter.pretty_print = false
exporter.years_of_history = 10
exporter.fhir.export = true
exporter.fhir_stu3.export = false
exporter.fhir_dstu2.export = false
exporter.fhir.use_us_core_ig = false
exporter.fhir.transaction_bundle = false
exporter.hospital.fhir.export = false
exporter.practitioner.fhir.export = false
exporter.csv.export = false
generate.thread_pool_size = 1
generate.demographics.default_file = geography/demographics.csv
generate.geography.zipcodes.default_file = geography/zipcodes.csv
generate.geography.country_code = CN
generate.geography.timezones.default_file = geography/timezones.csv
generate.geography.foreign.birthplace.default_file = geography/foreign_birthplace.json
generate.geography.sdoh.default_file = geography/sdoh.csv
generate.geography.passport_uri = urn:cn-health-data:synthetic-passport
generate.append_numbers_to_person_names = false
generate.providers.hospitals.default_file = providers/hospitals.csv
generate.providers.primarycare.default_file = providers/primary_care_facilities.csv
generate.providers.urgentcare.default_file = providers/urgent_care_facilities.csv
generate.providers.ihs.hospitals.default_file = 
generate.providers.ihs.primarycare.default_file = 
generate.providers.veterans.default_file = 
generate.providers.homehealth.default_file = 
generate.providers.hospice.default_file = 
generate.providers.nursing.default_file = 
generate.payers.insurance_companies.default_file = payers/insurance_companies.csv
generate.payers.insurance_plans.default_file = payers/insurance_plans.csv
generate.payers.insurance_plans.eligibilities_file = payers/insurance_eligibilities.csv
generate.payers.insurance_companies.medicare = 模拟基本医疗保险
generate.payers.insurance_companies.medicaid = 模拟基本医疗保险
generate.payers.insurance_companies.dual_eligible = 模拟基本医疗保险
generate.payers.selection_behavior = priority
generate.payers.loss_of_care = false
